# Generated by Django 3.2.7 on 2021-11-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
